
export interface Card {
  id: number;
  name: string;
  emoji: string;
  phrase: string; // Frase del cantador
}

export const LOTTERY_CARDS: Card[] = [
  { id: 1, name: "El Gallo", emoji: "🐓", phrase: "El que le cantó a San Pedro" },
  { id: 2, name: "El Diablito", emoji: "😈", phrase: "Pórtate bien cuatito" },
  { id: 3, name: "La Dama", emoji: "👸", phrase: "Puliendo el paso por toda la plaza" },
  { id: 4, name: "El Sombrero", emoji: "🎩", phrase: "Tan bonito y elegante" },
  { id: 5, name: "El Paraguas", emoji: "☂️", phrase: "Los usas para la lluvia" },
  { id: 6, name: "La Sirena", emoji: "🧜", phrase: "Con los encantos del mar" },
  { id: 7, name: "La Escalera", emoji: "🪜", phrase: "Súbete a ella y bajarás" },
  { id: 8, name: "La Botella", emoji: "🍾", phrase: "La herramienta del borracho" },
  { id: 9, name: "El Barril", emoji: "🛢️", phrase: "Tanto corre el que lo carga" },
  { id: 10, name: "El Árbol", emoji: "🌳", phrase: "El que a buen árbol se arrima" },
  { id: 11, name: "El Melón", emoji: "🍈", phrase: "Me lo das o me lo quitas" },
  { id: 12, name: "El Taco", emoji: "🌮", phrase: "El antojito mexicano" },
  { id: 13, name: "El Gorrito", emoji: "🎓", phrase: "Para la cabeza es" },
  { id: 14, name: "El Aguacate", emoji: "🥑", phrase: "Verde por fuera, oro por dentro" },
  { id: 15, name: "La Pera", emoji: "🍐", phrase: "El que espera desespera" },
  { id: 16, name: "La Bandera", emoji: "🇲🇽", phrase: "Verde, blanco y colorado" },
  { id: 17, name: "El Bandolón", emoji: "🪕", phrase: "Tocando su bandolón" },
  { id: 18, name: "El Violin", emoji: "🎻", phrase: "Instrumento de alegría" },
  { id: 19, name: "La Garza", emoji: "🦢", phrase: "Al otro lado del río" },
  { id: 20, name: "El Pájaro", emoji: "🐦", phrase: "Le cantaba a la luna" },
  { id: 21, name: "La Mano", emoji: "✋", phrase: "Del criminal la mano" },
  { id: 22, name: "La Bota", emoji: "🥾", phrase: "Una y otra vez la bota" },
  { id: 23, name: "La Luna", emoji: "🌙", phrase: "El farol de los enamorados" },
  { id: 24, name: "El Cotorro", emoji: "🦜", phrase: "Ave de mil colores" },
  { id: 25, name: "La Cerveza", emoji: "🍺", phrase: "La que se sube a la cabeza" },
  { id: 26, name: "El Circo", emoji: "🎪", phrase: "Payasos y acróbatas" },
  { id: 27, name: "El Corazón", emoji: "❤️", phrase: "No me extrañes corazón" },
  { id: 28, name: "La Sandía", emoji: "🍉", phrase: "La barriga que Juan tenía" },
  { id: 29, name: "El Tambor", emoji: "🥁", phrase: "No te arrugues cuero viejo" },
  { id: 30, name: "El Camarón", emoji: "🦐", phrase: "Camarón que se duerme" },
  { id: 31, name: "El Arco", emoji: "🏹", phrase: "Con su flecha y su arco" },
  { id: 32, name: "La Trompeta", emoji: "🎺", phrase: "Sonando la trompeta" },
  { id: 33, name: "La Araña", emoji: "🕷️", phrase: "Atarántamela a palos" },
  { id: 34, name: "El Casco", emoji: "🪖", phrase: "El sombrero del soldado" },
  { id: 35, name: "La Estrella", emoji: "⭐", phrase: "La guía de los marineros" },
  { id: 36, name: "El Cazo", emoji: "🍲", phrase: "El que sirve la comida" },
  { id: 37, name: "El Mundo", emoji: "🌍", phrase: "Este mundo es una bola" },
  { id: 38, name: "La Pluma", emoji: "🪶", phrase: "La pluma del escribano" },
  { id: 39, name: "El Nopal", emoji: "🌵", phrase: "Nopal de Castilla" },
  { id: 40, name: "El Alacrán", emoji: "🦂", phrase: "El que pica sin avisar" },
  { id: 41, name: "La Rosa", emoji: "🌹", phrase: "Rosita, Rosaura, Rosa" },
  { id: 42, name: "El Águila", emoji: "🦅", phrase: "El ave de la bandera" },
  { id: 43, name: "La Campana", emoji: "🔔", phrase: "Tú me tiras la campana" },
  { id: 44, name: "El Jarrón", emoji: "🏺", phrase: "El refresco del obrero" },
  { id: 45, name: "El Venado", emoji: "🦌", phrase: "Saltando va buscando" },
  { id: 46, name: "El Sol", emoji: "☀️", phrase: "El que a todos alumbra" },
  { id: 47, name: "La Corona", emoji: "👑", phrase: "La que usan los reyes" },
  { id: 48, name: "El Velero", emoji: "⛵", phrase: "Navegando por el mar" },
  { id: 49, name: "El Pino", emoji: "🌲", phrase: "Fresco y oloroso" },
  { id: 50, name: "El Pescado", emoji: "🐟", phrase: "El que por la boca muere" },
  { id: 51, name: "La Palmera", emoji: "🌴", phrase: "Palmera de la playa" },
  { id: 52, name: "La Planta", emoji: "🪴", phrase: "La que crece en la maceta" },
  { id: 53, name: "La Nota", emoji: "🎵", phrase: "Música para bailar" },
  { id: 54, name: "La Rana", emoji: "🐸", phrase: "Al ver que no podía" },
  { id: 55, name: "El Jalapeño", emoji: "🌶️", phrase: "¡El más picoso de todos!" } // ⭐ CARTA ESPECIAL
];
