// Mapeo de cartas a archivos de audio
export const CARD_AUDIO_MAP: Record<number, string> = {
  1: '/audio/cards/el-gallo.mp3',
  2: '/audio/cards/el-diablito.mp3',
  3: '/audio/cards/la-dama.mp3',
  4: '/audio/cards/el-catrin.mp3',
  5: '/audio/cards/el-paraguas.mp3',
  6: '/audio/cards/la-sirena.mp3',
  7: '/audio/cards/la-escalera.mp3',
  8: '/audio/cards/la-botella.mp3',
  9: '/audio/cards/el-barril.mp3',
  10: '/audio/cards/el-arbol.mp3',
  11: '/audio/cards/el-melon.mp3',
  12: '/audio/cards/el-valiente.mp3',
  13: '/audio/cards/el-gorrito.mp3',
  14: '/audio/cards/la-muerte.mp3',
  15: '/audio/cards/la-pera.mp3',
  16: '/audio/cards/la-bandera.mp3',
  17: '/audio/cards/el-bandolon.mp3',
  18: '/audio/cards/el-violoncello.mp3',
  19: '/audio/cards/la-garza.mp3',
  20: '/audio/cards/el-pajaro.mp3',
  21: '/audio/cards/la-mano.mp3',
  22: '/audio/cards/la-bota.mp3',
  23: '/audio/cards/la-luna.mp3',
  24: '/audio/cards/el-cotorro.mp3',
  25: '/audio/cards/el-borracho.mp3',
  26: '/audio/cards/el-negrito.mp3',
  27: '/audio/cards/el-corazon.mp3',
  28: '/audio/cards/la-sandia.mp3',
  29: '/audio/cards/el-tambor.mp3',
  30: '/audio/cards/el-camaron.mp3',
  31: '/audio/cards/las-jaras.mp3',
  32: '/audio/cards/el-musico.mp3',
  33: '/audio/cards/la-arana.mp3',
  34: '/audio/cards/el-soldado.mp3',
  35: '/audio/cards/la-estrella.mp3',
  36: '/audio/cards/el-cazo.mp3',
  37: '/audio/cards/el-mundo.mp3',
  38: '/audio/cards/el-apache.mp3',
  39: '/audio/cards/el-nopal.mp3',
  40: '/audio/cards/el-alacran.mp3',
  41: '/audio/cards/la-rosa.mp3',
  42: '/audio/cards/la-calavera.mp3',
  43: '/audio/cards/la-campana.mp3',
  44: '/audio/cards/el-cantarito.mp3',
  45: '/audio/cards/el-venado.mp3',
  46: '/audio/cards/el-sol.mp3',
  47: '/audio/cards/la-corona.mp3',
  48: '/audio/cards/la-chalupa.mp3',
  49: '/audio/cards/el-pino.mp3',
  50: '/audio/cards/el-pescado.mp3',
  51: '/audio/cards/la-palma.mp3',
  52: '/audio/cards/la-maceta.mp3',
  53: '/audio/cards/el-arpa.mp3',
  54: '/audio/cards/la-rana.mp3',
  55: '/audio/cards/el-jalapeno.mp3',
};

// Audio de efectos especiales
export const EFFECT_AUDIO = {
  victory: '/audio/effects/loteria-victory.mp3',
  cardMark: '/audio/effects/card-mark.mp3',
  gameStart: '/audio/effects/game-start.mp3',
  background: '/audio/effects/background-music.mp3',
};
